apiVersion: apps/v1
kind: Deployment
metadata:
  name: getcont
  labels:
    app: get
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get
  template:
    metadata:
      labels:
        app: get
    spec:
      containers:
      - name: get
        image: jonathanjhunt/sfia3-get
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: get-ip
  #namespace: pipeline
  labels:
    app: get-ip
spec:
  selector:
    app: get
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: ClusterIP
