apiVersion: apps/v1
kind: Deployment
metadata:
  name: updatecont
  labels:
    app: update
spec:
  replicas: 1
  selector:
    matchLabels:
      app: update
  template:
    metadata:
      labels:
        app: update
    spec:
      containers:
      - name: update
        image: qatrainingjaguila/sfia3-update
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: update-ip
  #namespace: pipeline
  labels:
    app: update-ip
spec:
  selector:
    app: update
  ports:
  - protocol: TCP
apiVersion: apps/v1
    port: 8084
    targetPort: 8084
apiVersion: apps/v1
  type: ClusterIP
